### ISSUE TITLE
KeyError with only 1 or 2 mapped spacers

### ISSUE THREAD

**Issue by snayfach** [Matteo-Ciciani/PAMpredict#3]
Hey Matteo - looks like the program is crashing when only 1 or 2 spacers are mapped:

> ESC[36m[2023-04-27 14:03:52] INFO:ESC[0m Reading matches...
> ESC[36m[2023-04-27 14:03:53] INFO:ESC[0m Filtering matches...
> ESC[36m[2023-04-27 14:03:53] WARNING:ESC[0m Only 1 mapped spacers, predictions might be inaccurate.
> ESC[36m[2023-04-27 14:03:53] INFO:ESC[0m Reading flanking sequences from phage databases...
> ESC[36m[2023-04-27 14:04:16] INFO:ESC[0m Realigning flanking regions...
> ESC[36m[2023-04-27 14:04:17] INFO:ESC[0m Flanking regions realignment completed!
> ESC[36m[2023-04-27 14:04:17] INFO:ESC[0m Generating PAM prediction...
> ESC[36m[2023-04-27 14:04:17] WARNING:ESC[0m No conserved base detected in either flanking sequences!
> ESC[36m[2023-04-27 14:04:17] INFO:ESC[0m Saving both flanking sequence logos...
> Traceback (most recent call last):
>   File "PAMpredict/PAMpredict/PAMpredict.py", line 67, in <module>
>     pam.predict()
>   File "PAMpredict/PAMpredict/predict_pam.py", line 190, in predict
>     self.save_prediction()
>   File "PAMpredict/PAMpredict/predict_pam.py", line 146, in save_prediction
>     pd.DataFrame(self.info_df['Downstream'][['A','C','G','T']]).to_csv(os.path.join(self.outdir, 'downstream_flanking_sequence_info.tsv'), sep='\t')
>   File "anaconda3/envs/PAMpredict/lib/python3.6/site-packages/pandas/core/frame.py", line 2912, in __getitem__
>     indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
>   File "anaconda3/envs/PAMpredict/lib/python3.6/site-packages/pandas/core/indexing.py", line 1254, in _get_listlike_indexer
>     self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
>   File "anaconda3/envs/PAMpredict/lib/python3.6/site-packages/pandas/core/indexing.py", line 1304, in _validate_read
> _indexer
>     raise KeyError(f"{not_found} not in index")
> KeyError: "['A'] not in index"

**Comment by Matteo-Ciciani** [comment]
Hi Stephen, thanks for letting me know, it should be fixed now.
